name: Build and upload APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Upload to release
    permissions:
      contents: write
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Create .env File
        run: |
          echo "SUPABASEURL=${{secrets.SUPABASEURL}}" >> .env
          echo "ANONKEY=${{secrets.ANONKEY}}" >> .env

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: 'stable'

      - name: verify flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Run Workflow
        id: write_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'experiment_keystore.jks'
          fileDir: "${RUNNER_TEMP}/keystore"
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Build APK and ios
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run:  flutter build apk --release --split-per-abi
      - run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload



        
